#!/usr/bin/env node
/******************************************************************************
 * Copyright (c) 2012 Alexander Kluth <derhartmut@niwohlos.org>               *
 *                                                                            *
 * Permission is hereby granted,  free of charge,  to any  person obtaining a *
 * copy of this software and associated documentation files (the "Software"), *
 * to deal in the Software without restriction,  including without limitation *
 * the rights to use,  copy, modify, merge, publish,  distribute, sublicense, *
 * and/or sell copies  of the  Software,  and to permit  persons to whom  the *
 * Software is furnished to do so, subject to the following conditions:       *
 *                                                                            *
 * The above copyright notice and this permission notice shall be included in *
 * all copies or substantial portions of the Software.                        *
 *                                                                            *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR *
 * IMPLIED, INCLUDING  BUT NOT  LIMITED TO THE WARRANTIES OF MERCHANTABILITY, *
 * FITNESS FOR A PARTICULAR  PURPOSE AND  NONINFRINGEMENT.  IN NO EVENT SHALL *
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER *
 * LIABILITY,  WHETHER IN AN ACTION OF CONTRACT,  TORT OR OTHERWISE,  ARISING *
 * FROM,  OUT OF  OR IN CONNECTION  WITH THE  SOFTWARE  OR THE  USE OR  OTHER *
 * DEALINGS IN THE SOFTWARE.                                                  *
 ******************************************************************************/
var cmd = require('./prompt');
var server = require('./server');
var data = require('./data');
var env = require('./env');
var config = require('./config');
var log = require('./log');
var argv = require('optimist').argv;

log.message("\nnyssrad 0.1 beta - noSQL key-value-database");
log.glitzer("Copyright (C) 2012 Alexander Kluth <derhartmut@niwohlos.org>");
log.message("Distributed under the terms of the MIT license\n");

// Parse the command line
if ((argv.store)) {
    log.warn('Loading store from file ' + argv.store + ', default store is not loaded!');
    data.setFilename(argv.store);
}

if (config.config.store.flush.interval) {
    data.registerFlushing();
}

data.load();
server.start();

if (config.config.env.prompt) {
    cmd.prompt();
}

